### ISSUE TITLE
I'm sorry and out of curiosity,what is that?

### ISSUE THREAD

**Issue by liuup** [uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu#12]

**Comment by NotNite** [comment]
this is a meme repo of sorts avenging https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee - GitHub closed it because it messed with their UI

they never fixed the bug after a year, so I'm avenging the repo by making u98u
